#!/bin/bash

src=~/dotfiles

for app in $src/*; do 
    if [ $(basename $app) == $(basename $0) ]; then continue; fi
    if [ $(basename $app) == README ]; then continue; fi

    while [ "$1" == "-i" ]; do
        read -p "Install dot files for $(basename $app)? (y/n) " yn
        case $yn in
            [Yy] | [Yy][Ee][Ss] ) yn=y; break;;
            [Nn] | [Nn][Oo] ) yn=n; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done
    if [ "$yn" != n ]; then 
        if [ -x $app/__custom_setup ]; then
            src=$app $app/__custom_setup
        else
            for dir_file in $src/$(basename $app)/*; do 

                if [ -d ~/.$(basename $dir_file) ]; then 
                    rm -r $1 ~/.$(basename $dir_file)
                fi
                ln -T -s $1 $dir_file ~/.$(basename $dir_file)
            done
        fi
    fi
done
