# vim: tw=0

# do nothing for noninteractive environments
#[ -z "$PS1" ] && return
[[ $- != *i* ]] && return


###choose editor
if type -P vim &> /dev/null; then
    export EDITOR='vim -p'
    alias vi=vim
elif type -P vi &> /dev/null; then
    export EDITOR=vi
    alias vim=vi
elif type -P emacs &> /dev/null; then
    export EDITOR=emacs
    alias vim=emacs
    alias vi=emacs
    echo 'Editor set to emacs. Make sure to use/setup <m-x>viper'
else
    echo 'No suitable editor found.'
fi

###choose pager
if type -P less &> /dev/null; then
    export PAGER=less
else
    export PAGER=more
    alias less=more
fi

###ubuntu calls ack ack-grep
if type -P ack-grep &> /dev/null; then
    alias ack=ack-grep
fi

#### gnome 256 colors
if [ "$COLORTERM" == "gnome-terminal" ]; then
    export TERM="xterm-256color"
fi


#### Vi mode & emacs-style clear
set -o vi
bind -m vi-insert "\C-l":clear-screen

# bash completion
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
elif [ -f /etc/bash_completion.d/vagrant ]; then
    . /etc/bash_completion.d/vagrant
elif [ -f /etc/bash_completion.d/git ]; then
    . /etc/bash_completion.d/git
elif [ -f /usr/local/etc/bash_completion.d/git-prompt.sh ]; then
    . /usr/local/etc/bash_completion.d/git-prompt.sh
elif [ -f /usr/local/etc/bash_completion.d/git-completion.sh ]; then
    . /usr/local/etc/bash_completion.d/git-completion.sh
fi


#for ls:
type -p dircolors > /dev/null && eval $(dircolors -b)


#date utilities
alias today='date +%F'
alias now="date +%FT%T"

#default behaviours
alias grep='grep --color=auto'
alias df='df -h'
if ls --version 2> /dev/null | grep GNU > /dev/null; then
    alias ls='ls --indicator-style=slash --human-readable --ignore-backups --color=auto --time-style=long-iso'
else
    alias ls='ls -p -h -G'
fi

#common mistakes
alias cd..='cd ..'

#compensate for missing software
if ! type -P feh &> /dev/null; then #use whatever gnome wants when no feh
    alias feh=gnome-open
    # TODO, use gnome-open,xdg-open, etc??
fi

#short cuts
alias ll='ls -l'
alias la='ls -la'

if [ $(type -p dtrx) ]; then
    alias x=dtrx
else
    alias x='tar xvf'
fi


# gui man viewer!
function gman {
    tmpfile=$(mktemp)
    man -t $1 > $tmpfile
    evince --sm-disable $tmpfile
    rm $tmpfile
}

# simple way to do reverse ssh tunnels
function rssh-proxy () {
    host=${2%:*}
    rport=${2#*:}
    ssh -R 0.0.0.0:$rport:127.0.0.1:$1 $host "echo tunnel available at $2&&cat"
}


if [ -f ~/.bashrc.local_ext ]; then
    . ~/.bashrc.local_ext
fi

export CDPATH=$HOME/code

LP_USER_ALWAYS=0
LP_SHOW_DIFF=0
LP_SHORT_PATH=1
. ~/.liquidprompt/liquidprompt
